### ISSUE TITLE
Expanded space for pagecontent

### ISSUE THREAD

**Issue by gjhagens** [vgsr/paascongres-2017#1]
To expand the space for page content, the following should be done:
1. Padding-values set to zero, in `class="entry-content"`
2. Box-shadow to 0px and top-padding-values & to zero, in `article id="post-##" class="post-## post type-post status-publish format-standard hentry category-geen-categorie"`.

![preview paascongres adjustments](https://cloud.githubusercontent.com/assets/8159179/19043844/17ea3506-8992-11e6-8511-43ac80ca1a6a.png)

Considering the usage of PageBuilder by SiteOrigin, it might be even a better idea to completely remove the margin- and padding-values to ensure that the plugin has acces to the entire width of the page. The plugin itself can easily add its own padding-values, if necessary.

Thanks alot!

**Comment by lmoffereins** [comment]
Aangezien we sinds kort Twenty Seventeen als parent theme gebruiken, is dit issue niet meer relevant.
